/**
 * Inlines assets/css/main.css's `@import` list into public/assets/css/style.css.
 *
 * The CSS half of what tsc is for assets/ts/: sources sit outside public/ so they are neither
 * web-served nor deployed, and the output is committed because deploy.sh rsyncs public/ straight
 * from the working tree. test/basic_test.sh rebuilds and diffs, so a forgotten build fails there
 * rather than shipping a stale stylesheet.
 *
 * `@import` is the source form and never the served one. Left in place the browser would discover
 * each part only after parsing the one before it — a serial chain of render-blocking requests, and
 * a typo'd href would 404 in silence with that component simply unstyled. Inlining costs the
 * browser nothing and turns both of those into a build error.
 *
 * Usage:
 *   node tools/build-css.mjs                 # writes public/assets/css/style.css
 *   node tools/build-css.mjs --out <path>    # writes elsewhere, for the drift check
 *
 * No dependencies — node alone, which the tests already need. Exits non-zero with the reason on
 * stderr; it never writes a partial file.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { ROOT, cli, read } from './build-cli.mjs';

const { fail, label, path } = cli('build-css', ['out']);

const ENTRY   = join(ROOT, 'assets/css/main.css');
const DEFAULT = join(ROOT, 'public/assets/css/style.css');

/** A CSS comment, non-greedy — the same shape HtmlTest strips before scanning selectors. */
const COMMENT = /\/\*[\s\S]*?\*\//g;

/** `@import url("x")`, `@import url(x)` and `@import "x"` — the three forms, one capture. */
const IMPORT = /@import\s+(?:url\(\s*(?:"([^"]*)"|'([^']*)'|([^)\s]*))\s*\)|"([^"]*)"|'([^']*)')\s*;/g;

/** Every file already inlined, so a part imported twice is an error rather than a duplicate rule. */
const seen = new Map();

/** Leaf files only — a manifest orders parts, it is not one. */
let parts = 0;

/**
 * A file either imports or declares, never both.
 *
 * That is what keeps the ordering decision in one kind of file: main.css says what comes before
 * what and nothing else, and a part says what it styles and never where it sits. A rule sitting in
 * a manifest would be an ordering decision made twice.
 *
 * @param {string} file
 * @param {string} importedBy
 * @returns {string}
 */
function inline(file, importedBy) {
  const previous = seen.get(file);

  if (previous !== undefined) {
    fail(`${label(file)} is imported twice — by ${previous} and by ${importedBy}.\n`
       + '            Every Tag case is styled by exactly one part; two imports would be two copies.');
  }

  seen.set(file, importedBy);

  const source = read(file) ?? fail(`${importedBy} imports ${label(file)}, which does not exist.`);

  const imports = [...source.replace(COMMENT, '').matchAll(IMPORT)]
    .map((match) => match.slice(1).find((group) => group !== undefined) ?? '');

  if (imports.length === 0) {
    parts += 1;

    return `/* ${label(file)} */\n${source.trim()}\n`;
  }

  // A manifest, so nothing may be left once the imports and the comments are taken out.
  const leftover = source.replace(COMMENT, '').replace(IMPORT, '').trim();

  if (leftover !== '') {
    fail(`${label(file)} imports and declares. A manifest holds only @import and comments;\n`
       + `            a rule in one would be an ordering decision made twice. Found: ${leftover.split('\n')[0]}`);
  }

  return imports
    .map((specifier) => {
      if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/)/i.test(specifier)) {
        fail(`${label(file)} imports "${specifier}". Only relative paths inside assets/css/ inline;\n`
           + '            anything else would still be a request the browser makes at run time.');
      }

      return inline(resolve(dirname(file), specifier), label(file));
    })
    .join('\n');
}

const out = path('out', DEFAULT);

const banner = `/* Generated by tools/build-css.mjs from ${label(ENTRY)} — do not edit.
 *
 * Edit the part named in the marker above each block, then run: npm run build
 * test/basic_test.sh rebuilds this file and diffs, so an edit made here is lost at the next build
 * and fails the verify script in the meantime.
 */\n`;

const css = `${banner}\n${inline(ENTRY, 'the build')}`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css, 'utf8');

console.log(`build-css: ${parts} parts → ${label(out)}`);
